"""Common contract shared by all LLM backends (OpenAI, Anthropic, Ollama, ...).

Every other part of the system (the agent loop, the tool registry) operates
exclusively on the types defined in this module. As a result, adding a new
provider only requires implementing `LLMProvider.complete()` in a new class,
with no changes needed anywhere else in the agent.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Role(str, Enum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


@dataclass
class ToolCall:
    """A tool invocation request generated by the model."""

    id: str
    name: str
    arguments: dict[str, Any]


@dataclass
class Message:
    """A single message in the conversation history, in provider-neutral form."""

    role: Role
    content: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)
    # The two fields below are only populated for TOOL-role messages —
    # they link a tool result back to the ToolCall from the ASSISTANT message.
    tool_call_id: str | None = None
    name: str | None = None


@dataclass
class ToolSchema:
    """Provider-independent description of a tool, expressed as JSON Schema."""

    name: str
    description: str
    parameters: dict[str, Any]


@dataclass
class LLMResponse:
    content: str | None
    tool_calls: list[ToolCall]
    raw: Any = None  # raw provider response, useful for logging/debugging
    finish_reason: str | None = None


class LLMProvider(ABC):
    """Abstraction over any LLM backend that supports function/tool calling."""

    @abstractmethod
    async def complete(
        self,
        messages: list[Message],
        tools: list[ToolSchema] | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Send the conversation history and available tools, return the model's response."""
        raise NotImplementedError
